const app=document.getElementById("app"), token=()=>localStorage.getItem("edt_token");
const api=async(url,opt={})=>{opt.headers={...(opt.headers||{}),"Content-Type":"application/json",...(token()?{Authorization:"Bearer "+token()}: {})};let r=await fetch(url,opt),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Erreur");return d};
function auth(){app.innerHTML=`<div class="card auth"><h1>🏫 EDT Scolaire</h1><p class="muted">Plateforme de création automatique des emplois du temps</p><div id="authbox"><h2>Connexion</h2><input id="email" placeholder="Email"><input id="password" type="password" placeholder="Mot de passe"><button class="primary" onclick="login()">Se connecter</button><button onclick="registerForm()">Créer un établissement</button><p id="msg"></p></div></div>`}
function registerForm(){document.getElementById("authbox").innerHTML=`<h2>Créer votre établissement</h2><input id="sname" placeholder="Nom de l'établissement"><input id="email" placeholder="Email administrateur"><input id="password" type="password" placeholder="Mot de passe (6 caractères minimum)"><button class="primary" onclick="register()">Créer le compte</button><button onclick="auth()">Retour</button><p id="msg"></p>`}
async function login(){try{let d=await api("/api/login",{method:"POST",body:JSON.stringify({email:email.value,password:password.value})});localStorage.setItem("edt_token",d.token);dashboard()}catch(e){msg.textContent=e.message}}
async function register(){try{let d=await api("/api/register",{method:"POST",body:JSON.stringify({name:sname.value,email:email.value,password:password.value})});localStorage.setItem("edt_token",d.token);dashboard()}catch(e){msg.textContent=e.message}}
async function dashboard(){if(!token())return auth();let me;try{me=await api("/api/me")}catch(e){localStorage.removeItem("edt_token");return auth()}app.innerHTML=`<header class="top"><div><b>EDT Scolaire</b><div class="muted" style="color:#d7eadf">${me.school.name}</div></div><button onclick="logout()">Déconnexion</button></header><main class="wrap"><div class="card"><h2>Configuration de l'établissement</h2><p class="muted">Ajoutez les données puis générez vos emplois du temps.</p><div class="three"><section><h3>Classes</h3><div class="row"><input id="newClass" placeholder="6e A"><button onclick="addItem('classes','newClass')">+</button></div><div id="classes" class="list"></div></section><section><h3>Salles</h3><div class="row"><input id="newRoom" placeholder="Salle 1"><button onclick="addItem('rooms','newRoom')">+</button></div><div id="rooms" class="list"></div></section><section><h3>Enseignants</h3><div class="row"><input id="newTeacher" placeholder="Nom"><button onclick="addItem('teachers','newTeacher')">+</button></div><div id="teachers" class="list"></div></section></div><hr><section><h3>Matières</h3><div class="row"><input id="newSubject" placeholder="Mathématiques"><input id="newHours" type="number" min="1" value="4" style="max-width:100px"><button onclick="addSubject()">+</button></div><div id="subjects" class="list"></div></section></div><div class="card"><h2>Génération</h2><div class="three"><label>Jours<select id="days"><option>5</option><option>6</option></select></label><label>Créneaux / jour<select id="periods"><option>6</option><option selected>7</option><option>8</option></select></label><label>&nbsp;<button class="primary" onclick="generate()">⚙ Générer</button></label></div></div><div id="results"></div></main>`;await loadAll()}
async function loadAll(){for(const t of ["classes","rooms","teachers","subjects"]){let a=await api("/api/"+t);document.getElementById(t).innerHTML=a.map(x=>`<span class="pill">${x.name}${x.hours?` (${x.hours}h)`:``} <button class="danger" onclick="del('${t}',${x.id})">×</button></span>`).join("")}}
async function addItem(t,id){let el=document.getElementById(id);if(!el.value.trim())return;await api("/api/"+t,{method:"POST",body:JSON.stringify({name:el.value})});el.value="";loadAll()}
async function addSubject(){let n=newSubject.value.trim();if(!n)return;await api("/api/subjects",{method:"POST",body:JSON.stringify({name:n,hours:+newHours.value||2})});newSubject.value="";loadAll()}
async function del(t,id){await api(`/api/${t}/${id}`,{method:"DELETE"});loadAll()}
async function generate(){try{let d=await api("/api/generate",{method:"POST",body:JSON.stringify({days:+days.value,periods:+periods.value})});render(d)}catch(e){alert(e.message)}}
function render(d){let names=["Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi"];results.innerHTML=`<div class="card"><div class="row noPrint"><h2 style="margin-right:auto">Emplois du temps</h2><button onclick="window.print()">🖨 Imprimer / PDF</button></div><div class="tabs">${d.classes.map((c,i)=>`<button class="${i?'':'active'}" onclick="showSchedule(${i})">${c.name}</button>`).join("")}</div>${d.classes.map((c,i)=>`<div class="tablewrap sched" data-i="${i}" style="display:${i?'none':'block'}"><table class="schedule"><thead><tr><th>Horaire</th>${names.slice(0,d.days).map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${Array.from({length:d.periods},(_,p)=>`<tr><th>${String(7+p).padStart(2,'0')}:00–${String(8+p).padStart(2,'0')}:00</th>${Array.from({length:d.days},(_,day)=>{let x=c.grid[day][p];return `<td>${x?`<div class="subject">${x.subject}</div><div class="room">${x.room}</div>`:"—"}</td>`}).join("")}</tr>`).join("")}</tbody></table></div>`).join("")}</div>`}
function showSchedule(i){document.querySelectorAll(".tabs button").forEach((b,n)=>b.classList.toggle("active",n===i));document.querySelectorAll(".sched").forEach((x,n)=>x.style.display=n===i?"block":"none")}
function logout(){localStorage.removeItem("edt_token");auth()}
token()?dashboard():auth();
